import re, os

cn_base = r"C:\Users\20606\Desktop\SCVC-github\cn\V3.0\08_工程极限\8.7_391项完整计算\卷9_末日倒计时_最后窗口_E201-E220"
en_base = r"C:\Users\20606\Desktop\SCVC-github\en\V3.0\08_Engineering_Limits\8.7_391_Calculations\Vol9_Doomsday_Countdown"

# Load master translations from batch_translate_v2.py
MASTER = []
with open(r"C:\Users\20606\Desktop\SCVC-github\batch_translate_v2.py", "r", encoding="utf-8") as f:
    exec_text = f.read()
start = exec_text.find("MASTER = [")
end = exec_text.find("\n\n# Files to process")
exec(exec_text[start:end])

# ========================
# E201: The Ice Age Lie
# ========================
E201_EXTRA = [
    # Title and subtitle
    ('# E201: SCVC气候物理 — "冰河期结束"是一个物理谎言', '# E201: SCVC Climate Physics — "The Ice Age Is Ending" Is a Physical Lie'),
    ('**输入**：SCVC常数（C=O键振动0.291 eV、H键0.20 eV、α=1/(4π³+π²+π)）、冰芯CO₂记录、Milankovitch轨道参数、同位素比率δ¹³C/¹⁴C', '**Inputs**: SCVC constants (C=O bond vibration 0.291 eV, H-bond 0.20 eV, α=1/(4π³+π²+π)), ice-core CO₂ records, Milankovitch orbital parameters, isotope ratios δ¹³C/¹⁴C'),
    ('**方法**：SCVC物理链 × 多指纹交叉验证 → 只有人类化石燃料能同时解释全部观测', '**Method**: SCVC physical chain × multi-fingerprint cross-validation → only human fossil fuels can simultaneously explain all observations'),
    ('**核心命题**：当前全球变暖不是冰河期的自然结束。SCVC的物理指纹锁死了"人类是唯一原因"的结论——每一个自然假说都至少与一个观测事实矛盾', '**Core Proposition**: Current global warming is not the natural end of an ice age. SCVC physical fingerprints lock down the conclusion that "humanity is the sole cause" — every natural hypothesis contradicts at least one observational fact'),

    # Section 1
    ('## §1. 速率：自然周期慢100倍', '## §1. Rate: Natural Cycles Are 100 Times Slower'),
    ('### 1.1 冰芯告诉我们什么', '### 1.1 What Ice Cores Tell Us'),
    ('南极冰芯（Vostok, EPICA Dome C）记录了80万年来的CO₂浓度。模式极其清晰：', 'Antarctic ice cores (Vostok, EPICA Dome C) record CO₂ concentrations over the past 800,000 years. The pattern is stark:'),
    ('冰期-间冰期循环中的CO₂变化：', 'CO₂ changes during glacial-interglacial cycles:'),
    ('末次冰消期 (LGM→全新世):', 'Last deglaciation (LGM → Holocene):'),
    ('过去80万年的典型间冰期过渡:', 'Typical interglacial transitions over the past 800,000 years:'),
    ('当前 (工业化至今, 1850–2024):', 'Present (industrialization to date, 1850–2024):'),
    ('**速率比 = 0.93 / 0.0094 ≈ 100 倍**（相对于末次冰消期）', '**Rate ratio = 0.93 / 0.0094 ≈ 100×** (relative to the last deglaciation)'),
    ('C=O键不对称伸缩振动（0.291 eV = 2347 cm⁻¹）是CO₂温室效应的分子源头。', 'The C=O asymmetric stretching vibration (0.291 eV = 2347 cm⁻¹) is the molecular origin of the CO₂ greenhouse effect.'),
    ('CO₂的红外吸收截面是物理常数——每增加1 ppm CO₂的辐射强迫是固定的。', 'The infrared absorption cross-section of CO₂ is a physical constant — the radiative forcing per 1 ppm CO₂ increase is fixed.'),
    ('温室效应的速率 ∝ CO₂增加速率。', 'The rate of the greenhouse effect ∝ CO₂ increase rate.'),
    ('自然冰期-间冰期过渡的CO₂增加速率是0.01-0.02 ppm/年。', 'The CO₂ increase rate during natural glacial-interglacial transitions is 0.01-0.02 ppm/year.'),
    ('当前的速率是0.93 ppm/年。', 'The current rate is 0.93 ppm/year.'),
    ('→ 快了50-100倍。', '→ 50-100 times faster.'),
    ('→ 自然过程不可能在150年内完成需要8000年的工作。', '→ Natural processes cannot accomplish in 150 years what took 8,000 years.'),
    ('→ 必须有额外的、快速的碳源。', '→ There must be an additional, fast carbon source.'),
    ('### 1.2 不仅是速率——还有总量', '### 1.2 Not Just the Rate — Also the Total Amount'),
    ('如果当前CO₂上升是自然周期：', 'If the current CO₂ rise were a natural cycle:'),
    ('需要自然源在150年内释放 ~297 GtC（大气增量）', 'Natural sources would need to release ~297 GtC (atmospheric increase) in 150 years'),
    ('可能的自然源：', 'Possible natural sources:'),
    ('火山: 0.3 GtC/年 × 150年 = 45 GtC', 'Volcanoes: 0.3 GtC/year × 150 years = 45 GtC'),
    ('差6.6倍', '6.6× short'),
    ('海洋: 净吸收 ~2.5 GtC/年', 'Oceans: net absorption ~2.5 GtC/year'),
    ('是碳汇,不是源', 'are a carbon sink, not a source'),
    ('永冻土: 0.4 GtC/年 × 150年 = 60 GtC', 'Permafrost: 0.4 GtC/year × 150 years = 60 GtC'),
    ('差5倍', '5× short'),
    ('所有自然源合计: <0.7 GtC/年 × 150年 ≈ 105 GtC', 'All natural sources combined: <0.7 GtC/year × 150 years ≈ 105 GtC'),
    ('实际大气增量: ~297 GtC', 'Actual atmospheric increase: ~297 GtC'),
    ('缺口: 297 − 105 = 192 GtC — 自然源只能解释35%', 'Gap: 297 − 105 = 192 GtC — natural sources can only explain 35%'),
    ('而人类排放: ~10 GtC/年 × 150年 ≈ 700 GtC', 'Meanwhile, human emissions: ~10 GtC/year × 150 years ≈ 700 GtC'),
    ('（其中~297留在大气, ~170入海, ~230入陆地生物圈）', '(of which ~297 remains in the atmosphere, ~170 enters the ocean, ~230 enters the land biosphere)'),
    ('→ 碳预算完美闭合：人类排放 = 大气增量 + 海洋吸收 + 陆地吸收', '→ Carbon budget closes perfectly: human emissions = atmospheric increase + ocean absorption + land absorption'),
    ('→ 没有给"神秘自然源"留下空间', '→ No room left for a "mysterious natural source"'),

    # Section 2
    ('## §2. 方向：我们现在应该走向冰期', '## §2. Direction: We Should Be Heading Toward an Ice Age'),
    ('### 2.1 Milankovitch周期——地球的轨道恒温器', '### 2.1 Milankovitch Cycles — Earth Orbital Thermostat'),
    ('Milankovitch三参数决定了北半球高纬度夏季日照量——', 'The three Milankovitch parameters determine summer insolation at high northern latitudes —'),
    ('这是冰期-间冰期循环的"起搏器"：', 'this is the "pacemaker" of glacial-interglacial cycles:'),
    ('当前的轨道配置：', 'Current orbital configuration:'),
    ('偏心率: 0.017 (低,近圆形 → 岁差效应弱)', 'Eccentricity: 0.017 (low, near-circular → weak precession effect)'),
    ('倾角:   23.4° (中等,缓慢减小中)', 'Obliquity: 23.4° (moderate, slowly decreasing)'),
    ('进动:   北半球夏至接近远日点', 'Precession: Northern Hemisphere summer solstice near aphelion'),
    ('→ 北半球65°N夏季日照量: 正在缓慢下降', '→ Northern Hemisphere 65°N summer insolation: slowly declining'),
    ('→ 最近一次日照峰值: ~10,000年前 (全新世气候适宜期)', '→ Most recent insolation peak: ~10,000 years ago (Holocene Climate Optimum)'),
    ('→ 按照轨道理论: 我们现在应该进入缓慢降温阶段', '→ According to orbital theory: we should now be entering a slow cooling phase'),
    ('→ 在数万年后走向下一个冰期', '→ heading toward the next glacial in tens of thousands of years'),
    ('SCVC与Milankovitch的关系：', 'The relationship between SCVC and Milankovitch:'),
    ('轨道力学是引力问题——与SCVC常数（α, m_e等）无关。', 'Orbital mechanics is a gravitational problem — independent of SCVC constants (α, m_e, etc.).'),
    ('这是一个独立于SCVC的天文学事实。', 'This is an astronomical fact independent of SCVC.'),
    ('但SCVC提供了一个额外的验证：', 'But SCVC provides an additional verification:'),
    ('→ 日照变化幅度（~0.5-2 W/m²在北纬65°N夏季）', '→ Insolation variation amplitude (~0.5-2 W/m² at 65°N summer)'),
    ('→ 远小于当前温室气体强迫（~3 W/m²,全球年均）', '→ far smaller than current greenhouse gas forcing (~3 W/m², global annual average)'),
    ('→ 人类温室效应已经压倒轨道信号', '→ the human greenhouse effect has already overwhelmed the orbital signal'),
    ('### 2.2 方向矛盾', '### 2.2 The Direction Contradiction'),
    ('Milankovitch预测: 缓慢降温（走向冰期的入口）', 'Milankovitch prediction: slow cooling (entering the gateway to a glacial)'),
    ('实际观测:         剧烈升温（+1.2°C，加速中）', 'Actual observation: rapid warming (+1.2°C, accelerating)'),
    ('预测方向   实际方向', 'Predicted direction   Actual direction'),
    ('↓ 降温      ↑ 升温', '↓ cooling      ↑ warming'),
    ('← 方向完全相反 →', '← directions are completely opposite →'),
    ('→ 这排除了"冰河期自然结束"的假说。', '→ This rules out the "natural end of an ice age" hypothesis.'),
    ('→ 冰河期结束应该是数千年前的事（全新世气候适宜期）。', '→ The ice age ended thousands of years ago (Holocene Climate Optimum).'),
    ('→ 当前的变暖是在自然降温趋势上的反向加速。', '→ Current warming is a reverse acceleration superimposed on a natural cooling trend.'),
    ('→ 必须有强大的非轨道强迫 → 温室气体。', '→ There must be a powerful non-orbital forcing → greenhouse gases.'),

    # Section 3
    ('## §3. 同位素指纹：化石燃料的"DNA"', '## §3. Isotope Fingerprint: The "DNA" of Fossil Fuels'),
    ('这是SCVC能提供的最强单个证据。', 'This is the strongest single piece of evidence SCVC can provide.'),
    ('### 3.1 碳-13：Suess效应', '### 3.1 Carbon-13: The Suess Effect'),
    ('碳有三种稳定同位素: ¹²C (98.9%), ¹³C (1.1%), ¹⁴C (放射性)', 'Carbon has three isotopes: ¹²C (98.9%), ¹³C (1.1%), ¹⁴C (radioactive)'),
    ('不同碳源的δ¹³C值不同:', 'Different carbon sources have different δ¹³C values:'),
    ('碳源              δ¹³C (‰)       为什么', 'Carbon source       δ¹³C (‰)       Why'),
    ('化石燃料          −25 to −30     古生物→偏好轻同位素', 'Fossil fuels        −25 to −30     Ancient organisms → prefer light isotopes'),
    ('陆地生物圈        −25             光合作用→RuBisCO歧视¹³C', 'Terrestrial biosphere −25           Photosynthesis → RuBisCO discriminates against ¹³C'),
    ('火山CO₂           ~−5             地幔碳→接近原始值', 'Volcanic CO₂        ~−5             Mantle carbon → near primordial value'),
    ('海洋溶解无机碳    ~0 to +2        海水碳酸盐平衡', 'Ocean dissolved inorganic C ~0 to +2  Seawater carbonate equilibrium'),
    ('大气CO₂(工业化前)  −6.4           历史基线', 'Atmospheric CO₂ (pre-industrial) −6.4  Historical baseline'),
    ('大气CO₂(当前)      −8.6           观测值', 'Atmospheric CO₂ (current) −8.6         Observed value'),
    ('SCVC——C=O键振动与同位素:', 'SCVC — C=O bond vibration and isotopes:'),
    ('C=O伸缩振动频率 ν ∝ √(k/μ)', 'C=O stretching vibrational frequency ν ∝ √(k/μ)'),
    ('其中 μ = m_C·m_O/(m_C+m_O) 是约化质量', 'where μ = m_C·m_O/(m_C+m_O) is the reduced mass'),
    ('¹³C比¹²C重8.3%，约化质量略高', '¹³C is 8.3% heavier than ¹²C, with slightly higher reduced mass'),
    ('→ ¹³C=O振动频率略低于¹²C=O', '→ ¹³C=O vibrational frequency is slightly lower than ¹²C=O'),
    ('→ 两者的红外吸收峰略有不同', '→ The infrared absorption peaks of the two differ slightly'),
    ('→ 可以精确测量大气CO₂中¹³C/¹²C的比率', '→ The ¹³C/¹²C ratio in atmospheric CO₂ can be precisely measured'),
    ('SCVC的C=O键能(3.5 eV)和振动能(0.291 eV)给出了', 'SCVC C=O bond energy (3.5 eV) and vibrational energy (0.291 eV) provide'),
    ('键的劲度系数 → 谱线位置的计算基础', 'the bond stiffness coefficient → the basis for calculating spectral line positions'),
    ('质量平衡分析:', 'Mass balance analysis:'),
    ('工业化前: 280 ppm CO₂, δ¹³C = −6.4‰', 'Pre-industrial: 280 ppm CO₂, δ¹³C = −6.4‰'),
    ('当前:     420 ppm CO₂, δ¹³C = −8.6‰', 'Current: 420 ppm CO₂, δ¹³C = −8.6‰'),
    ('新增大气的碳必须有轻的同位素特征。', 'The carbon newly added to the atmosphere must have a light isotopic signature.'),
    ('如果新增碳来自:', 'If the added carbon comes from:'),
    ('火山:         需要 δ¹³C ≈ −5‰   → 与观测矛盾 (大气δ¹³C会上升或不变)', 'Volcanoes:     would need δ¹³C ≈ −5‰   → contradicts observation (atmospheric δ¹³C would rise or stay the same)'),
    ('海洋释放:     需要 δ¹³C ≈ 0‰    → 与观测严重矛盾', 'Ocean release: would need δ¹³C ≈ 0‰    → severely contradicts observation'),
    ('化石燃料:     δ¹³C ≈ −28‰       → 与观测方向一致', 'Fossil fuels:  δ¹³C ≈ −28‰       → consistent with observed direction'),
    ('陆地生物圈:   δ¹³C ≈ −25‰       → 方向一致，但生物圈是净碳汇', 'Terrestrial biosphere: δ¹³C ≈ −25‰ → direction consistent, but biosphere is a net carbon sink'),
    ('→ 只有化石燃料（或大规模毁林）能解释δ¹³C的下降方向', '→ Only fossil fuels (or massive deforestation) can explain the downward direction of δ¹³C'),
    ('→ 毁林本身也是人类活动', '→ Deforestation itself is also a human activity'),

    # 3.2 C-14
    ('### 3.2 碳-14：绝对杀手', '### 3.2 Carbon-14: The Absolute Killer'),
    ('半衰期: 5,730 年', 'Half-life: 5,730 years'),
    ('产生: 宇宙射线与上层大气中的¹⁴N反应', 'Production: cosmic rays react with ¹⁴N in the upper atmosphere'),
    ('自然丰度: ~1.2×10⁻¹² (¹⁴C/¹²C)', 'Natural abundance: ~1.2×10⁻¹² (¹⁴C/¹²C)'),
    ('石油/煤/天然气是数百万年前的古生物', 'Oil/coal/natural gas are ancient organisms from millions of years ago'),
    ('→ 所有¹⁴C已完全衰变（数万个半衰期）', '→ All ¹⁴C has completely decayed (tens of thousands of half-lives)'),
    ('→ 化石燃料的¹⁴C含量 = 0', '→ ¹⁴C content of fossil fuels = 0'),
    ('→ 向大气注入不含¹⁴C的CO₂', '→ Inject CO₂ containing zero ¹⁴C into the atmosphere'),
    ('→ 稀释大气¹⁴C/¹²C比率', '→ Dilute the atmospheric ¹⁴C/¹²C ratio'),
    ('→ 观测到大气Δ¹⁴C下降 ~−30‰到−50‰', '→ Observed atmospheric Δ¹⁴C decline ~−30‰ to −50‰'),
    ('（扣除1950-60年代核试验的¹⁴C脉冲后）', '(after removing the ¹⁴C pulse from 1950s-60s nuclear testing)'),
    ('火山CO₂含有现代¹⁴C（地幔碳在上升过程中混合了地表碳）。', 'Volcanic CO₂ contains modern ¹⁴C (mantle carbon mixes with surface carbon during ascent).'),
    ('海洋CO₂含有现代¹⁴C。', 'Ocean CO₂ contains modern ¹⁴C.'),
    ('→ 只有化石燃料能解释¹⁴C的稀释效应。', '→ Only fossil fuels can explain the ¹⁴C dilution effect.'),
    ('→ 这是"冒烟的枪"——不可辩驳的物理证据。', '→ This is the "smoking gun" — irrefutable physical evidence.'),

    # Section 4
    ('## §4. 平流层冷却：太阳变暖的排除', '## §4. Stratospheric Cooling: Ruling Out Solar Warming'),
    ('### 4.1 两种变暖的垂直指纹', '### 4.1 The Vertical Fingerprints of Two Types of Warming'),
    ('温室气体变暖          太阳亮度增加', 'Greenhouse gas warming          Increased solar brightness'),
    ('对流层 (0-15 km)    升温 ✓                升温 ✓', 'Troposphere (0-15 km)    warming ✓                warming ✓'),
    ('平流层 (15-50 km)   降温 ✓                升温 ✗', 'Stratosphere (15-50 km)  cooling ✓                warming ✗'),
    ('观测结果:            平流层在降温', 'Observational result:    the stratosphere is cooling'),
    ('→ 排除了"太阳变亮"', '→ Rules out "brighter sun"'),
    ('→ 确认了温室气体机制', '→ Confirms the greenhouse gas mechanism'),
    ('### 4.2 SCVC的物理解释', '### 4.2 SCVC Physical Explanation'),
    ('平流层降温的物理:', 'The physics of stratospheric cooling:'),
    ('CO₂在对流层: 捕获地表红外辐射 → 加热低层大气', 'CO₂ in the troposphere: traps surface infrared radiation → heats the lower atmosphere'),
    ('CO₂在平流层:', 'CO₂ in the stratosphere:'),
    ('① 吸收来自下方对流层的上行红外辐射', '① Absorbs upwelling infrared radiation from the troposphere below'),
    ('② 在低气压下，分子碰撞频率低 → 碰撞退激发慢', '② At low pressure, molecular collision frequency is low → collisional de-excitation is slow'),
    ('③ 辐射退激发快 → CO₂分子将能量辐射到太空', '③ Radiative de-excitation is fast → CO₂ molecules radiate energy to space'),
    ('净效应: 更多CO₂ → 平流层更高效地向太空散热 → 降温', 'Net effect: more CO₂ → stratosphere dissipates heat to space more efficiently → cooling'),
    ('这是温室气体变暖的独特"指纹"。', 'This is a unique "fingerprint" of greenhouse gas warming.'),
    ('太阳变暖会同时加热对流层和平流层。', 'Solar warming would heat both the troposphere and stratosphere simultaneously.'),
    ('SCVC补充:', 'SCVC supplement:'),
    ('C=O键的振动激发态寿命 ∝ 1/(自发辐射Einstein A系数)', 'Vibrational excited state lifetime of the C=O bond ∝ 1/(spontaneous emission Einstein A coefficient)'),
    ('A系数从C=O键的跃迁偶极矩推导 → 最终从α推导', 'The A coefficient is derived from the transition dipole moment of the C=O bond → ultimately derived from α'),
    ('→ 在低气压(<10 hPa)下，辐射退激发 > 碰撞退激发', '→ At low pressure (<10 hPa), radiative de-excitation > collisional de-excitation'),
    ('→ 平流层冷却是可精确计算的', '→ Stratospheric cooling is precisely calculable'),

    # Section 5
    ('## §5. 海洋的证据：pH与热量', '## §5. Ocean Evidence: pH and Heat'),
    ('### 5.1 海洋酸化——海洋是碳汇，不是碳源', '### 5.1 Ocean Acidification — The Ocean Is a Carbon Sink, Not a Carbon Source'),
    ('海洋pH: 8.2 (工业化前) → 8.1 (当前)', 'Ocean pH: 8.2 (pre-industrial) → 8.1 (current)'),
    ('→ [H⁺] 增加了 ~26%', '→ [H⁺] has increased ~26%'),
    ('如果海洋是碳源（释放CO₂）→ pH应该上升（更碱性）', 'If the ocean were a carbon source (releasing CO₂) → pH should rise (more alkaline)'),
    ('实际pH在下降（更酸性）   → 海洋在吸收CO₂', 'Actual pH is falling (more acidic) → the ocean is absorbing CO₂'),
    ('→ 海洋是碳汇，吸收约25%的人类排放', '→ The ocean is a carbon sink, absorbing ~25% of human emissions'),
    ('→ "海洋释放CO₂导致变暖"的假说与pH数据直接矛盾', '→ The "ocean releasing CO₂ causes warming" hypothesis directly contradicts pH data'),
    ('### 5.2 海洋热量——460太瓦的"额外暖器"', '### 5.2 Ocean Heat — 460 Terawatts of "Extra Heater"'),
    ('地球能量不平衡: ~0.9 W/m² (净吸热)', 'Earth energy imbalance: ~0.9 W/m² (net heat absorption)'),
    ('地球表面积:     5.1×10¹⁴ m²', 'Earth surface area: 5.1×10¹⁴ m²'),
    ('总超额功率:     ~460 TW (太瓦)', 'Total excess power: ~460 TW (terawatts)'),
    ('≈ 每秒7颗广岛原子弹的额外热量', '≈ 7 Hiroshima bombs per second of extra heat'),
    ('≈ 每天60万颗广岛原子弹', '≈ 600,000 Hiroshima bombs per day'),
    ('≈ 每年2.3亿颗广岛原子弹', '≈ 230 million Hiroshima bombs per year'),
    ('— 持续了30年以上', '— sustained for over 30 years'),
    ('海洋上层2000m已累积: ~4×10²² J', 'Upper 2000m of ocean has accumulated: ~4×10²² J'),
    ('水的比热容 c_p = 4200 J/kg/K', 'Water specific heat capacity c_p = 4200 J/kg/K'),
    ('← 来自水的H键网络（0.20 eV/H键）', '← from water H-bond network (0.20 eV/H-bond)'),
    ('← H键是异常高比热容的分子原因', '← H-bonds are the molecular cause of the anomalously high specific heat capacity'),
    ('← 也是为什么海洋能吸收如此巨大的热量', '← also why the ocean can absorb such enormous heat'),
    ('而表面温度只上升了~1°C的原因', 'while surface temperature has only risen ~1°C'),

    # Section 6
    ('## §6. 最终判决矩阵', '## §6. Final Judgment Matrix'),
    ('假说', 'Hypothesis'),
    ('预测', 'Prediction'),
    ('观测', 'Observation'),
    ('判决', 'Verdict'),
    ('**冰河期自然结束**', '**Ice age ending naturally**'),
    ('缓慢升温 (0.01 ppm/yr)', 'Slow warming (0.01 ppm/yr)'),
    ('急速升温 (0.93 ppm/yr)', 'Rapid warming (0.93 ppm/yr)'),
    ('❌ 排除（速率差100倍）', '❌ Ruled out (rate differs 100×)'),
    ('**太阳变亮**', '**Brighter sun**'),
    ('平流层升温', 'Stratospheric warming'),
    ('平流层降温', 'Stratospheric cooling'),
    ('❌ 排除（垂直指纹相反）', '❌ Ruled out (vertical fingerprint opposite)'),
    ('**火山排放增加**', '**Increased volcanic emissions**'),
    ('δ¹³C ≈ −5‰', 'δ¹³C ≈ −5‰'),
    ('δ¹³C = −8.6‰', 'δ¹³C = −8.6‰'),
    ('❌ 排除（同位素不匹配）', '❌ Ruled out (isotope mismatch)'),
    ('**海洋释放CO₂**', '**Ocean releasing CO₂**'),
    ('pH上升（去酸化）', 'pH rise (de-acidification)'),
    ('pH下降（酸化）', 'pH fall (acidification)'),
    ('❌ 排除（方向相反）', '❌ Ruled out (direction opposite)'),
    ('**Milankovitch周期**', '**Milankovitch cycles**'),
    ('走向冰期（降温）', 'Heading toward glacial (cooling)'),
    ('剧烈升温', 'Rapid warming'),
    ('❌ 排除（方向相反）', '❌ Ruled out (direction opposite)'),
    ('**人类燃烧化石燃料**', '**Human combustion of fossil fuels**'),
    ('CO₂↑ + δ¹³C↓ + pH↓ + 平流层↓ + 速率↑', 'CO₂↑ + δ¹³C↓ + pH↓ + stratosphere↓ + rate↑'),
    ('CO₂↑ + δ¹³C↓ + pH↓ + 平流层↓ + 速率↑', 'CO₂↑ + δ¹³C↓ + pH↓ + stratosphere↓ + rate↑'),
    ('✅ 全部一致', '✅ All consistent'),

    # SCVC contribution
    ('SCVC的核心贡献:', 'SCVC Core Contribution:'),
    ('这六个物理指纹不是随机的——它们是从SCVC常数可以正向推导的:', 'These six physical fingerprints are not random — they can be forward-derived from SCVC constants:'),
    ('① 速率 → C=O振动0.291eV → 固定了每ppm CO₂的辐射强迫', '① Rate → C=O vibration 0.291eV → fixes radiative forcing per ppm CO₂'),
    ('→ 固定了升温对CO₂增量的敏感度', '→ fixes the sensitivity of warming to CO₂ increase'),
    ('→ 自然速率不可能匹配当前观测', '→ natural rates cannot match current observations'),
    ('② 方向 → Milankovitch轨道 → 独立的天文学事实', '② Direction → Milankovitch orbits → independent astronomical fact'),
    ('→ 与SCVC无关,但与温室效应叠加', '→ independent of SCVC, but superimposes with the greenhouse effect'),
    ('③ δ¹³C → C=O键的约化质量效应 → ¹³C vs ¹²C振动频率差', '③ δ¹³C → C=O bond reduced mass effect → ¹³C vs ¹²C vibrational frequency difference'),
    ('→ 光谱可区分 → Suess效应的物理基础', '→ spectroscopically distinguishable → physical basis of the Suess effect'),
    ('④ ¹⁴C → 核物理(β衰变,半衰期5730年)', '④ ¹⁴C → nuclear physics (β decay, half-life 5,730 years)'),
    ('→ 与SCVC弱耦合,但化石燃料的零¹⁴C是地质事实', '→ weakly coupled to SCVC, but zero ¹⁴C in fossil fuels is a geological fact'),
    ('⑤ 平流层冷却 → C=O振动激发态寿命 → 辐射vs碰撞退激发', '⑤ Stratospheric cooling → C=O vibrational excited state lifetime → radiative vs collisional de-excitation'),
    ('→ 在低气压下的竞争 → 冷却指纹', '→ competition at low pressure → cooling fingerprint'),
    ('⑥ 海洋酸化 → H键0.20eV → 水的高比热容和CO₂溶解化学', '⑥ Ocean acidification → H-bond 0.20eV → water high specific heat and CO₂ dissolution chemistry'),
    ('→ 海洋作为热容缓冲和碳汇的物理基础', '→ physical basis of the ocean as heat capacity buffer and carbon sink'),

    # Section 7
    ('## §7. 工程结论', '## §7. Engineering Conclusions'),
    ('### 7.1 这是物理学，不是政治学', '### 7.1 This Is Physics, Not Politics'),
    ('六条独立的物理证据链，每一条都指向同一结论。', 'Six independent physical evidence chains, each pointing to the same conclusion.'),
    ('不是"大多数科学家认为"——是物理常数不允许其他解释。', 'It is not "most scientists think" — it is that physical constants permit no other explanation.'),
    ('→ 速率: 自然周期的最快速率比当前慢50-100倍', '→ Rate: the fastest natural cycle rate is 50-100× slower than current'),
    ('→ 方向: Milankovitch预测降温，实际在升温', '→ Direction: Milankovitch predicts cooling; reality is warming'),
    ('→ 同位素: 化石燃料的¹³C和¹⁴C指纹无法伪造', '→ Isotopes: the ¹³C and ¹⁴C fingerprints of fossil fuels cannot be faked'),
    ('→ 平流层: 温室气体独有的冷却指纹', '→ Stratosphere: the cooling fingerprint unique to greenhouse gases'),
    ('→ 海洋: pH下降证明海洋在吸收CO₂，不是释放', '→ Ocean: falling pH proves the ocean is absorbing CO₂, not releasing it'),
    ('→ 碳预算: 人类排放 = 大气增量 + 海洋吸收 + 陆地吸收（完美闭合）', '→ Carbon budget: human emissions = atmospheric increase + ocean absorption + land absorption (closes perfectly)'),
    ('否定气候变化的人需要同时否定这六条独立的物理证据链。', 'Climate change deniers would need to simultaneously negate these six independent physical evidence chains.'),
    ('这不是一个观点——这是一个六重交叉验证的物理结论。', 'This is not an opinion — it is a sixfold cross-validated physical conclusion.'),
    ('### 7.2 与E199（气候末日钟）的联动', '### 7.2 Linkage with E199 (Climate Doomsday Clock)'),
    ('E199给出了"什么都不做"的时间线——基于CO₂排放速率和反馈。', 'E199 provided the "do nothing" timeline — based on CO₂ emission rates and feedbacks.'),
    ('E201证明了这条时间线是人类自己画的——不是自然周期。', 'E201 proves that this timeline is drawn by humanity itself — not by natural cycles.'),
    ('人类在以比自然冰期过渡快100倍的速度改写大气化学。', 'Humanity is rewriting atmospheric chemistry 100× faster than natural glacial transitions.'),
    ('以前的物种有8000年适应100 ppm的CO₂变化。', 'Past species had 8,000 years to adapt to a 100 ppm CO₂ change.'),
    ('现在的物种只有150年适应140 ppm的CO₂变化。', 'Current species have only 150 years to adapt to a 140 ppm CO₂ change.'),
    ('SCVC的终极判断:', 'SCVC Ultimate Judgment:'),
    ('适应时间缩短了50-100倍。', 'Adaptation time has shortened by a factor of 50-100.'),
    ('灭绝率会相应上升。', 'Extinction rates will rise accordingly.'),
    ('不是因为温度本身——是因为速度。', 'Not because of the temperature itself — because of the speed.'),
    ('### 7.3 "以前也暖过"的正确理解', '### 7.3 Correctly Understanding "It Was Warm Before"'),
    ('"以前也暖过" — 是的。但:', '"It was warm before" — yes. But:'),
    ('① 最后两次暖期之间隔了~10万年 — 生命有适应时间', '① The last two warm periods were separated by ~100,000 years — life had time to adapt'),
    ('② PETM (5600万年前)升温~5-8°C — 但用了~2万年', '② PETM (56 million years ago) warmed ~5-8°C — but took ~20,000 years'),
    ('当前升温~1.2°C — 只用了~150年', 'Current warming ~1.2°C — took only ~150 years'),
    ('→ PETM速率: ~0.0003°C/年', '→ PETM rate: ~0.0003°C/year'),
    ('→ 当前速率: ~0.008°C/年', '→ Current rate: ~0.008°C/year'),
    ('→ 快 ~25倍, 且在加速', '→ ~25× faster, and accelerating'),
    ('③ 二叠纪末(2.52亿年前)升温~8-12°C — 用了~100万年', '③ End-Permian (252 million years ago) warmed ~8-12°C — took ~1 million years'),
    ('当前轨迹如不加控制 → 可能在200-300年内达到类似升温', 'Current trajectory if unchecked → could reach similar warming in 200-300 years'),
    ('→ 快3000-5000倍', '→ 3,000-5,000× faster'),
    ('SCVC的结论:', 'SCVC Conclusion:'),
    ('"以前也暖过"这个说法忽略了一个关键物理量——速率。', 'The statement "it was warm before" ignores a crucial physical quantity — rate.'),
    ('碳循环的速率（GtC/年）决定了生态系统能否跟上。', 'The rate of the carbon cycle (GtC/year) determines whether ecosystems can keep up.'),
    ('跟上意味着物种迁徙、进化、适应。', 'Keeping up means species migrate, evolve, and adapt.'),
    ('跟不上意味着灭绝。', 'Failing to keep up means extinction.'),
    ('人类正在以地质记录中前所未有的速率改变碳循环。', 'Humanity is altering the carbon cycle at a rate unprecedented in the geological record.'),
    ('这不是"和以前一样"——这是"比以前快100-5000倍"。', 'This is not "same as before" — this is "100-5,000× faster than before."'),

    # Appendices
    ('## 附录A：本次使用的SCVC常数', '## Appendix A: SCVC Constants Used in This Document'),
    ('符号', 'Symbol'),
    ('用途', 'Purpose'),
    ('C=O伸缩振动', 'C=O stretch vibration'),
    ('CO₂红外吸收 → 辐射强迫系数5.35', 'CO₂ IR absorption → radiative forcing coefficient 5.35'),
    ('C-O键能', 'C-O bond energy'),
    ('CO₂分子稳定性 → 大气寿命', 'CO₂ molecular stability → atmospheric lifetime'),
    ('H键能', 'H-bond energy'),
    ('水的高比热容(4200 J/kg/K) → 海洋热容', 'Water high specific heat (4200 J/kg/K) → ocean heat capacity'),
    ('分子极化率 → 吸收截面 → 温室效应强度', 'Molecular polarizability → absorption cross-section → greenhouse effect strength'),
    ('分子碰撞频率 → 平流层辐射vs碰撞竞争', 'Molecular collision frequency → stratospheric radiation vs collision competition'),
    ('T⁴辐射 → 地球能量平衡', 'T⁴ radiation → Earth energy balance'),
    ('## 附录B：关键公式速查', '## Appendix B: Key Formula Quick Reference'),
    ('CO₂辐射强迫:         ΔF = 5.35 × ln(C/C₀) W/m²', 'CO₂ radiative forcing:   ΔF = 5.35 × ln(C/C₀) W/m²'),
    ('(5.35 从C=O吸收截面推导,最终追溯到α)', '(5.35 derived from C=O absorption cross-section, ultimately traceable to α)'),
    ('碳预算:              E_human = ΔC_atm + U_ocean + U_land', 'Carbon budget:           E_human = ΔC_atm + U_ocean + U_land'),
    ('(闭合验证——没有神秘自然源的空间)', '(closure verification — no room for a mysterious natural source)'),
    ('同位素质量平衡:       C₁·δ₁ + C_added·δ_source = C₂·δ₂', 'Isotope mass balance:    C₁·δ₁ + C_added·δ_source = C₂·δ₂'),
    ('(δ¹³C下降只能用轻碳源解释 → 化石燃料)', '(δ¹³C decline can only be explained by a light carbon source → fossil fuels)'),
    ('平流层冷却:           低气压: τ_radiative < τ_collisional', 'Stratospheric cooling:   low pressure: τ_radiative < τ_collisional'),
    ('→ CO₂向太空辐射热量 → 冷却指纹', '→ CO₂ radiates heat to space → cooling fingerprint'),
    ('海洋酸化:             CO₂ + H₂O ⇌ H⁺ + HCO₃⁻', 'Ocean acidification:     CO₂ + H₂O ⇌ H⁺ + HCO₃⁻'),
    ('[H⁺]增加 → pH下降 → 海洋是碳汇', '[H⁺] increase → pH decline → ocean is a carbon sink'),
    ('速率比:               R = (140 ppm/150 yr) / (100 ppm/7500 yr) ≈ 70', 'Rate ratio:              R = (140 ppm/150 yr) / (100 ppm/7,500 yr) ≈ 70'),
    ('→ 人类排放比自然冰期转变快约两个数量级', '→ human emissions are about two orders of magnitude faster than natural glacial transitions'),
    ('本文档从SCVC常数(C=O键振动0.291 eV)+同位素物理+轨道力学+碳循环的多指纹交叉验证，证明当前全球变暖不是冰河期的自然结束。六个独立物理证据链指向同一结论——人类燃烧化石燃料。这不是政治观点，是物理常数不允许其他解释。速率（GtC/年）比总量（GtC）更重要——而人类正在以地质记录中前所未有的速率改写大气化学。', 'This document uses SCVC constants (C=O bond vibration 0.291 eV) + isotope physics + orbital mechanics + multi-fingerprint cross-validation of the carbon cycle to prove that current global warming is not the natural end of an ice age. Six independent physical evidence chains point to the same conclusion — human combustion of fossil fuels. This is not a political opinion; physical constants permit no other explanation. Rate (GtC/year) matters more than total amount (GtC) — and humanity is rewriting atmospheric chemistry at a rate unprecedented in the geological record.'),
]

# Apply to E201
src_path = os.path.join(cn_base, "E201_冰河期谎言.md")
dst_path = os.path.join(en_base, "E201_Ice_Age_Lie.md")

with open(src_path, "r", encoding="utf-8") as f:
    content = f.read()

# Apply master first
for old, new in MASTER:
    if old in content:
        content = content.replace(old, new)

# Apply E201-specific
replaced = 0
for old, new in E201_EXTRA:
    if old in content:
        content = content.replace(old, new)
        replaced += 1

cn = len(re.findall(r'[\u4e00-\u9fff]', content))
with open(dst_path, "w", encoding="utf-8") as f:
    f.write(content)
print(f"E201: {cn} CN / {len(content)} total ({round(cn/len(content)*100,1)}%) - {replaced} replacements")
