import os, sys

cn_base = r"C:\Users\20606\Desktop\SCVC-github\cn\V3.0\08_工程极限\8.7_391项完整计算"
en_base = r"C:\Users\20606\Desktop\SCVC-github\en\V3.0\08_Engineering_Limits\8.7_391_Calculations"

# EXTENDED master dictionary
MASTER = [
    # Headers
    ("SCVC工程极限", "SCVC Engineering Limit"),
    ("基于**：`_SCVC工程常数速查表.md` (全π多项式推导，零自由参数，2.22 ppm精度)", "Based on: `_SCVC Engineering Constants Reference.md` (all-π-polynomial derivation, zero free parameters, 2.22 ppm precision)"),
    ("基于**：`_SCVC工程常数速查表.md`", "Based on: `_SCVC Engineering Constants Reference.md`"),
    ("所有推导基于SCVC常数速查表（零自由参数，α=1/(4π³+π²+π)）。", "All derivations are based on the SCVC constant reference table (zero free parameters, α=1/(4π³+π²+π))."),
    ("工程师可直接使用结论，无需理解SCVC几何推导。", "Engineers may directly use the conclusions without understanding the SCVC geometric derivation."),
    ("工程结论", "Engineering Conclusions"),
    ("速查决策表", "Quick-Reference Decision Table"),
    ("推导链", "Derivation Chain"),
    ("硬输入", "Hard Inputs"),
    ("SCVC硬输入", "SCVC Hard Inputs"),
    ("SCVC 输入参数", "SCVC Input Parameters"),
    ("自旋电子学", "Spintronics"),
    ("上限", "Ceiling"),
    ("极限", "Limit"),
    ("天花板", "Ceiling"),
    
    # Time/date
    ("计算日期", "Calculation Date"),
    ("derived日期", "Calculation Date"),
    ("基于", "Based on"),
    ("版本", "Version"),
    ("日期", "Date"),
    
    # Section headers - common
    ("方法论", "Methodology"),
    ("理论抗拉强度", "Theoretical Tensile Strength"),
    ("比强度（强度/密度）", "Specific Strength (Strength / Density)"),
    ("杨氏模量上限", "Young Modulus Ceiling"),
    ("催化活化能下限", "Catalytic Activation Energy Lower Bound"),
    ("过渡态理论框架", "Transition State Theory Framework"),
    ("电催化上限", "Electrocatalysis Ceiling"),
    ("电催化过电位总汇", "Electrocatalysis Overpotential Summary"),
    ("光催化", "Photocatalysis"),
    ("光解水", "Water Photolysis"),
    ("人工光合作用", "Artificial Photosynthesis"),
    ("带隙要求", "Bandgap Requirements"),
    ("附录：计算细节", "Appendix: Calculation Details"),
    ("工程意义", "Engineering Significance"),
    ("核心主张", "Core Claim"),
    ("共同特征", "Common Features"),
    ("和其他领域的区别", "Comparison with Other Domains"),
    ("SCVC的判断", "SCVC Judgment"),
    ("SCVC判定", "SCVC Verdict"),
    ("SCVC的推导链", "SCVC Derivation Chain"),
    ("你认得这些", "What You Recognize"),
    ("如果 §2 的推导正确", "If §2 Derivation Is Correct"),
    ("你的验证路径", "Your Verification Path"),
    ("验证路径", "Verification Path"),
    ("找推导链裂缝", "Find cracks in the derivation chain"),
    ("找反例", "Find counterexamples"),
    ("一个反例就够了", "One counterexample suffices"),
    ("对手方向", "Competitor Directions"),
    
    # Table headers
    ("物理量", "Quantity"),
    ("符号", "Symbol"),
    ("实验", "Experiment"),
    ("偏差", "Deviation"),
    ("状态", "Status"),
    ("参数", "Parameter"),
    ("值", "Value"),
    ("来源", "Source"),
    ("排名", "Rank"),
    ("材料", "Material"),
    ("类型", "Type"),
    ("判据", "Verdict"),
    ("评估", "Assessment"),
    ("差距", "Gap"),
    ("问题", "Question"),
    ("SCVC 答案", "SCVC Answer"),
    ("当前最优", "Current Best"),
    ("SCVC极限", "SCVC Limit"),
    ("当前水平", "Current Level"),
    ("SCVC允许", "SCVC Permits"),
    ("距极限差距", "Gap to Limit"),
    ("反应", "Reaction"),
    ("当前最佳", "Current Best"),
    ("触达", "Reached"),
    ("停滞", "Stalled"),
    ("一直以来的解释", "Conventional Explanation"),
    ("你的领域一直在试图", "What Your Field Keeps Trying"),
    ("温区", "Temperature Zone"),
    ("温度", "Temperature"),
    ("物理判定", "Physical Verdict"),
    ("材料路线", "Material Route"),
    ("结论", "Conclusion"),
    ("内容", "Content"),
    ("方向", "Direction"),
    ("SCVC 贡献", "SCVC Contribution"),
    ("行动建议", "Action Recommendation"),
    ("需要新技术吗", "Requires New Technology?"),
    ("物理允许性", "Physical Permissibility"),
    ("可行性评估", "Feasibility Assessment"),
    ("可行性判定", "Feasibility Assessment"),
    ("备注", "Notes"),
    ("名称", "Name"),
    ("含义", "Meaning"),
    ("领域", "Domain"),
    ("天花板", "Ceiling"),
    ("当前", "Current"),
    ("理论值", "Theoretical"),
    ("实验值", "Experimental"),
    ("实验最佳", "Best Experimental"),
    ("无实验", "No experiment"),
    ("预测", "Prediction"),
    
    # Status markers
    ("物理允许", "Physically permitted"),
    ("已锁定", "Locked"),
    ("已实现", "Achieved"),
    ("已成熟", "mature"),
    ("发展中", "developing"),
    ("接近极限", "Near limit"),
    ("触顶", "At ceiling"),
    ("极小", "Minimal"),
    ("中等", "Moderate"),
    ("不可逾越的墙", "Insurmountable wall"),
    
    # Common technical phrases
    ("速查表", "reference table"),
    ("键能", "bond energy"),
    ("键长", "bond length"),
    ("力常数", "force constant"),
    ("理论derived", "theoretical derivation"),
    ("理论强度", "theoretical strength"),
    ("缺陷折减", "defect reduction"),
    ("金刚石", "Diamond"),
    ("石墨烯", "Graphene"),
    ("碳纳米管", "CNT"),
    ("碳炔", "Carbyne"),
    ("碳纤维", "carbon fiber"),
    ("钛合金", "Titanium alloy"),
    ("马氏体时效钢", "Maraging steel"),
    ("绝对上限", "absolute upper bound"),
    ("理论上限", "theoretical upper bound"),
    ("工程实际", "engineering reality"),
    ("室温", "room temperature"),
    ("室温超导", "room-temperature superconductivity"),
    ("超导", "superconducting"),
    ("光伏", "photovoltaic"),
    ("核聚变", "nuclear fusion"),
    ("电池快充", "battery fast charging"),
    ("碳捕获", "carbon capture"),
    ("碳捕集", "carbon capture"),
    ("制氢", "hydrogen production"),
    ("氢能", "hydrogen energy"),
    ("芯片频率", "chip frequency"),
    ("量子计算", "quantum computing"),
    ("AI训练能耗", "AI training energy"),
    ("脑机接口", "brain-computer interface"),
    ("光子通信", "photonic communication"),
    ("量子比特", "qubit"),
    ("相干时间", "coherence time"),
    ("DNA存储", "DNA storage"),
    ("最大寿命", "maximum lifespan"),
    ("寿命", "lifespan"),
    ("神经传导速度", "nerve conduction velocity"),
    ("自由意志", "free will"),
    ("意识", "consciousness"),
    ("语言信息率", "language information rate"),
    ("肌肉功率", "muscle power"),
    ("癌症", "cancer"),
    ("HIV治愈", "HIV cure"),
    ("阿尔茨海默", "Alzheimer"),
    ("衰老速率", "aging rate"),
    ("衰老回拨", "aging reversal"),
    ("长寿方案", "longevity protocol"),
    ("人类休眠", "human hibernation"),
    ("基因编辑", "gene editing"),
    ("基因治疗", "gene therapy"),
    ("血脑屏障", "blood-brain barrier"),
    ("免疫逃逸", "immune escape"),
    ("抗生素耐药", "antibiotic resistance"),
    ("通用流感疫苗", "universal flu vaccine"),
    ("广谱抗病毒", "broad-spectrum antiviral"),
    ("病毒错误灾难", "viral error catastrophe"),
    ("自身免疫病", "autoimmune disease"),
    ("真菌体温防火墙", "fungal body-temperature firewall"),
    ("地震震级", "earthquake magnitude"),
    ("海啸波高", "tsunami wave height"),
    ("火山规模", "volcano scale"),
    ("日食", "solar eclipse"),
    ("龙卷风", "tornado"),
    ("闪电", "lightning"),
    ("冰川", "glacier"),
    ("降雨率", "rainfall rate"),
    ("最高树高", "maximum tree height"),
    ("最高瀑布", "maximum waterfall height"),
    ("行星地质", "planetary geology"),
    ("小行星偏转", "asteroid deflection"),
    ("风暴强度", "storm intensity"),
    ("全球变暖", "global warming"),
    ("AMOC崩溃", "AMOC collapse"),
    ("气候末日钟", "climate doomsday clock"),
    ("甲烷水合物", "methane hydrate"),
    ("厄尔尼诺", "El Nino"),
    ("超级火山", "supervolcano"),
    ("盲审模拟", "blind review simulation"),
    ("SCVCvsSM", "SCVC vs SM"),
    ("SCVC区间性质", "SCVC Interval Properties"),
    ("AI的自白", "AI Confession"),
    ("关键区别", "Key Differences"),
    ("补遗", "Addendum"),
    
    # Medicine-specific
    ("无毒多靶点癌症封杀", "Non-Toxic Multi-Target Cancer Lockout"),
    ("无毒多靶点封杀", "Non-Toxic Multi-Target Lockout"),
    ("癌细胞分裂上限", "Cancer Cell Division Ceiling"),
    ("癌细胞分裂速度上限", "Cancer Cell Division Rate Ceiling"),
    ("癌症不可能三角", "Cancer Impossible Triangle"),
    ("突变时间窗口上限", "Mutation Time Window Ceiling"),
    ("肿瘤血管极限上限", "Tumor Vascular Limit Ceiling"),
    ("免疫逃逸矛盾上限", "Immune Escape Paradox Ceiling"),
    ("综合", "Comprehensive"),
    ("物理突破口", "Physical Breakthrough"),
    ("四线并行实验方案", "Four-Line Parallel Experimental Protocol"),
    ("动物加速", "Animal Acceleration"),
    ("今天就开", "Start Today"),
    ("药物设计上限", "Drug Design Ceiling"),
    ("药物结合亲和力上限", "Drug Binding Affinity Ceiling"),
    ("酶催化速率上限", "Enzyme Catalytic Rate Ceiling"),
    ("酶最优工作区间", "Enzyme Optimal Operating Range"),
    ("医学成像上限", "Medical Imaging Ceiling"),
    ("放射治疗上限", "Radiotherapy Ceiling"),
    ("基因编辑上限", "Gene Editing Ceiling"),
    ("免疫应答速度上限", "Immune Response Speed Ceiling"),
    ("伤口愈合最大速率", "Wound Healing Maximum Rate"),
    ("耐药天花板", "Resistance Ceiling"),
    ("医学革命", "Medical Revolution"),
    ("锁死工程菌", "Lockdown Engineered Bacteria"),
    ("癌细胞预防锁", "Cancer Cell Prevention Lock"),
    ("共生菌群进化锁定", "Symbiotic Microbiome Evolutionary Lock"),
    ("长寿_物理路径", "Longevity: Physical Pathway"),
    ("回拨衰老_可逆性", "Aging Reversal: Reversibility"),
    ("完整长寿方案_休眠_冗余_纳米维护", "Complete Longevity Protocol: Hibernation, Redundancy, Nano-Maintenance"),
    ("神经元纳米维护频率", "Neuron Nano-Maintenance Frequency"),
    ("冷冻vs休眠", "Cryopreservation vs Hibernation"),
    ("人类休眠定量方案", "Human Hibernation Quantitative Protocol"),
    ("耐药天花板_医学革命", "Resistance Ceiling: Medical Revolution"),
    
    # Standard phrases
    ("注：", "Note: "),
    ("条件：", "Conditions:"),
    ("结论：", "Conclusion:"),
    ("本章所有数值上限来自SCVC常数的理论推导，不代表工程可实现性。", "All numerical ceilings in this chapter are derived from SCVC constant theory and do not represent engineering realizability."),
    ("* 本文所有数值上限来自SCVC常数的理论推导，不代表工程可实现性。", "* All numerical ceilings in this document are derived from SCVC constant theory and do not represent engineering realizability."),
    ("* SCVC 常数精度 2.22 ppm，相应推导误差在可忽略量级。", "* SCVC constant precision is 2.22 ppm; corresponding derivation errors are negligible."),
    ("所有物理极限均由 SCVC 工程常数速查表提供的键能/键长/力常数推导。任何超过这些极限的声称将意味着超越已知物理。", "All physical limits are derived from bond energies / bond lengths / force constants provided by the SCVC Engineering Constants Reference. Any claim exceeding these limits would imply surpassing known physics."),
    ("催化极限由标度关系决定，而标度关系来自化学键的普遍性。", "Catalysis limits are determined by scaling relations, which arise from the universality of chemical bonds."),
    ("SCVC框架将键能锁定在3.6-9.8 eV，由此导出所有催化边界。", "The SCVC framework locks bond energies at 3.6-9.8 eV, from which all catalytic boundaries are derived."),
    ("SCVC 常数精度 2.22 ppm，相应推导误差在可忽略量级。", "SCVC constant precision is 2.22 ppm; corresponding derivation errors are negligible."),
    
    # Correction patterns for mixed output
    ("磁性Material上限", "Magnetic Materials Ceiling"),
    ("Material上限", "Materials Ceiling"),
    ("Current室温", "Current room-temperature"),
    ("Current Best", "Current Best"),
    ("Current最高", "Current highest"),
    ("物理极限", "physical limit"),
    ("推导链的裂缝", "cracks in the derivation chain"),
    ("验推导链", "Verify the derivation chain"),
    ("一个就可以", "Just one will do"),
    ("不是\"恰好", "not \"it happens to be"),
    ("不是\"没", "not \"hasn"),
    ("距离理论上限", "Distance to theoretical limit"),
    ("距理论上限", "Distance to theoretical limit"),
    ("提升空间", "headroom"),
    
    # Common standalone words that should be English
    ("Temperature", "temperature"),
    ("derived", "derived"),
    ("Parameter", "parameter"),
    ("Value", "value"),
    ("Material", "material"),
    ("Current", "current"),
    ("Energy", "energy"),
]

# Files to process
FILES = [
    # Vol1 - Materials & Structures (already processed with old dict)
    ("卷1_材料与结构", "E1_超导_Tc上限.md", "Vol1_Materials_Structures", "E1_Superconducting_Tc_Ceiling.md"),
    ("卷1_材料与结构", "E4_结构材料上限.md", "Vol1_Materials_Structures", "E4_Structural_Materials_Ceiling.md"),
    ("卷1_材料与结构", "E5_催化上限.md", "Vol1_Materials_Structures", "E5_Catalysis_Ceiling.md"),
    ("卷1_材料与结构", "E6_磁性材料上限.md", "Vol1_Materials_Structures", "E6_Magnetic_Materials_Ceiling.md"),
    ("卷1_材料与结构", "E9_航天推进上限.md", "Vol1_Materials_Structures", "E9_Space_Propulsion_Ceiling.md"),
    ("卷1_材料与结构", "E33_反应速率Arrhenius上限.md", "Vol1_Materials_Structures", "E33_Reaction_Rate_Arrhenius_Ceiling.md"),
    ("卷1_材料与结构", "E42_火箭复用上限.md", "Vol1_Materials_Structures", "E42_Rocket_Reusability_Ceiling.md"),
    ("卷1_材料与结构", "E56_最高熔点.md", "Vol1_Materials_Structures", "E56_Maximum_Melting_Point.md"),
    ("卷1_材料与结构", "E57_最大热导率.md", "Vol1_Materials_Structures", "E57_Maximum_Thermal_Conductivity.md"),
    ("卷1_材料与结构", "E163_催化剂TOF上限.md", "Vol1_Materials_Structures", "E163_Catalyst_TOF_Ceiling.md"),
    # Vol2 - Electronics & Computing
    ("卷2_电子与计算", "E8_量子计算上限.md", "Vol2_Electronics_Computing", "E8_Quantum_Computing_Ceiling.md"),
    ("卷2_电子与计算", "E44_AI训练能耗上限.md", "Vol2_Electronics_Computing", "E44_AI_Training_Energy_Ceiling.md"),
    ("卷2_电子与计算", "E48_晶体管能耗上限.md", "Vol2_Electronics_Computing", "E48_Transistor_Energy_Ceiling.md"),
    ("卷2_电子与计算", "E49_芯片频率上限.md", "Vol2_Electronics_Computing", "E49_Chip_Frequency_Ceiling.md"),
    ("卷2_电子与计算", "E15_计算物理上限.md", "Vol2_Electronics_Computing", "E15_Computation_Physics_Ceiling.md"),
    ("卷2_电子与计算", "E26_脑机接口上限.md", "Vol2_Electronics_Computing", "E26_Brain_Computer_Interface_Ceiling.md"),
    ("卷2_电子与计算", "E60_光子通信上限.md", "Vol2_Electronics_Computing", "E60_Photonic_Communication_Ceiling.md"),
    ("卷2_电子与计算", "E160_量子比特相干时间.md", "Vol2_Electronics_Computing", "E160_Qubit_Coherence_Time.md"),
    ("卷2_电子与计算", "E164_DNA存储密度上限.md", "Vol2_Electronics_Computing", "E164_DNA_Storage_Density_Ceiling.md"),
    ("卷2_电子与计算", "E14_光学光子学上限.md", "Vol2_Electronics_Computing", "E14_Optics_Photonics_Ceiling.md"),
    # Vol3 - Energy & Environment
    ("卷3_能源与环境", "E3_光伏半导体上限.md", "Vol3_Energy_Environment", "E3_Photovoltaic_Semiconductor_Ceiling.md"),
    ("卷3_能源与环境", "E159_核聚变Q值上限.md", "Vol3_Energy_Environment", "E159_Fusion_Q_Value_Ceiling.md"),
    ("卷3_能源与环境", "E22_电池快充上限.md", "Vol3_Energy_Environment", "E22_Battery_Fast_Charge_Ceiling.md"),
    ("卷3_能源与环境", "E41_碳捕获上限.md", "Vol3_Energy_Environment", "E41_Carbon_Capture_Ceiling.md"),
    ("卷3_能源与环境", "E40_制氢上限.md", "Vol3_Energy_Environment", "E40_Hydrogen_Production_Ceiling.md"),
    ("卷3_能源与环境", "E7_核能上限.md", "Vol3_Energy_Environment", "E7_Nuclear_Energy_Ceiling.md"),
    ("卷3_能源与环境", "E2_化学储能上限.md", "Vol3_Energy_Environment", "E2_Chemical_Energy_Storage_Ceiling.md"),
    ("卷3_能源与环境", "E161_碳捕集最小能量.md", "Vol3_Energy_Environment", "E161_Carbon_Capture_Minimum_Energy.md"),
    # Vol4 - Human Biophysics
    ("卷4_人类生物物理", "E88_最大寿命上限.md", "Vol4_Human_Biophysics", "E88_Maximum_Lifespan_Ceiling.md"),
    ("卷4_人类生物物理", "E28_神经传导速度上限.md", "Vol4_Human_Biophysics", "E28_Nerve_Conduction_Velocity_Ceiling.md"),
    ("卷4_人类生物物理", "E96_自由意志.md", "Vol4_Human_Biophysics", "E96_Free_Will.md"),
    ("卷4_人类生物物理", "E99_意识是什么.md", "Vol4_Human_Biophysics", "E99_What_Is_Consciousness.md"),
    ("卷4_人类生物物理", "E82_语言信息率上限.md", "Vol4_Human_Biophysics", "E82_Language_Information_Rate_Ceiling.md"),
    ("卷4_人类生物物理", "E69_肌肉功率上限.md", "Vol4_Human_Biophysics", "E69_Muscle_Power_Ceiling.md"),
    # Vol5 - Medicine & Drugs (selected ~12 key files)
    ("卷5_医学与药物", "E168-E171_综合_癌症不可能三角与物理突破口.md", "Vol5_Medicine_Drugs", "E168-E171_Cancer_Impossible_Triangle_Physical_Breakthrough.md"),
    ("卷5_医学与药物", "E172_无毒多靶点癌症封杀.md", "Vol5_Medicine_Drugs", "E172_Non_Toxic_Multi_Target_Cancer_Lockout.md"),
    ("卷5_医学与药物", "E172_无毒多靶点封杀上限.md", "Vol5_Medicine_Drugs", "E172_Non_Toxic_Multi_Target_Lockout_Ceiling.md"),
    ("卷5_医学与药物", "E176_HIV治愈上限.md", "Vol5_Medicine_Drugs", "E176_HIV_Cure_Ceiling.md"),
    ("卷5_医学与药物", "E178_阿尔茨海默上限.md", "Vol5_Medicine_Drugs", "E178_Alzheimer_Ceiling.md"),
    ("卷5_医学与药物", "E179_衰老速率地板上限.md", "Vol5_Medicine_Drugs", "E179_Aging_Rate_Floor_Ceiling.md"),
    ("卷5_医学与药物", "E186_长寿_物理路径.md", "Vol5_Medicine_Drugs", "E186_Longevity_Physical_Pathway.md"),
    ("卷5_医学与药物", "E187_回拨衰老_可逆性.md", "Vol5_Medicine_Drugs", "E187_Aging_Reversal_Reversibility.md"),
    ("卷5_医学与药物", "E188_完整长寿方案_休眠_冗余_纳米维护.md", "Vol5_Medicine_Drugs", "E188_Complete_Longevity_Protocol.md"),
    ("卷5_医学与药物", "E191_人类休眠定量方案.md", "Vol5_Medicine_Drugs", "E191_Human_Hibernation_Quantitative_Protocol.md"),
    ("卷5_医学与药物", "E183_癌细胞预防锁.md", "Vol5_Medicine_Drugs", "E183_Cancer_Cell_Prevention_Lock.md"),
    ("卷5_医学与药物", "E43_基因编辑上限.md", "Vol5_Medicine_Drugs", "E43_Gene_Editing_Ceiling.md"),
    # Vol6 - Earth & Astronomy (selected ~4)
    ("卷6_地球与天体", "E78_地震震级上限.md", "Vol6_Earth_Astronomy", "E78_Earthquake_Magnitude_Ceiling.md"),
    ("卷6_地球与天体", "E80_海啸波高上限.md", "Vol6_Earth_Astronomy", "E80_Tsunami_Wave_Height_Ceiling.md"),
    ("卷6_地球与天体", "E81_火山规模上限.md", "Vol6_Earth_Astronomy", "E81_Volcano_Scale_Ceiling.md"),
    ("卷6_地球与天体", "E129_日食上限.md", "Vol6_Earth_Astronomy", "E129_Solar_Eclipse_Ceiling.md"),
    # Vol8b - Methodology & Humanities (all 6)
    ("卷8b_方法论与人文", "E200_盲审模拟.md", "Vol8b_Methodology_Humanities", "E200_Blind_Review_Simulation.md"),
    ("卷8b_方法论与人文", "E131_SCVC区间性质.md", "Vol8b_Methodology_Humanities", "E131_SCVC_Interval_Properties.md"),
    ("卷8b_方法论与人文", "E132_SCVCvsSM.md", "Vol8b_Methodology_Humanities", "E132_SCVC_vs_SM.md"),
    ("卷8b_方法论与人文", "E132_SCVCvsSM_关键区别.md", "Vol8b_Methodology_Humanities", "E132_SCVC_vs_SM_Key_Differences.md"),
    ("卷8b_方法论与人文", "E132_SCVCvsSM_补遗.md", "Vol8b_Methodology_Humanities", "E132_SCVC_vs_SM_Addendum.md"),
    ("卷8b_方法论与人文", "AI的自白_从E1到E126的对话与觉醒.md", "Vol8b_Methodology_Humanities", "AI_Confession_E1_to_E126_Dialogue_Awakening.md"),
]

print(f"Master dictionary: {len(MASTER)} entries")
print(f"Files to process: {len(FILES)}")

count = 0
for src_sub, src_name, dst_sub, dst_name in FILES:
    src_path = os.path.join(cn_base, src_sub, src_name)
    dst_path = os.path.join(en_base, dst_sub, dst_name)
    
    if not os.path.exists(src_path):
        print(f"SKIP (missing): {src_name}")
        continue
    
    with open(src_path, "r", encoding="utf-8") as f:
        content = f.read()
    
    # Apply master translations
    for old, new in MASTER:
        content = content.replace(old, new)
    
    os.makedirs(os.path.dirname(dst_path), exist_ok=True)
    with open(dst_path, "w", encoding="utf-8") as f:
        f.write(content)
    
    count += 1
    print(f"OK: {dst_name}")

print(f"\n=== Done: {count} files ===")
