import sys, os

cn_dir = r"C:\Users\20606\Desktop\SCVC-github\cn\V3.0\08_工程极限\8.7_391项完整计算"
en_dir = r"C:\Users\20606\Desktop\SCVC-github\en\V3.0\08_Engineering_Limits\8.7_391_Calculations"

def translate_file(src, dst, translations):
    with open(src, "r", encoding="utf-8") as f:
        content = f.read()
    for old, new in translations:
        content = content.replace(old, new)
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    with open(dst, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"OK: {os.path.basename(dst)}")

# Common translations used across files
T_COMMON = [
    ("所有推导基于SCVC常数速查表（零自由参数，α=1/(4π³+π²+π)）。", "All derivations are based on the SCVC constant reference table (zero free parameters, α=1/(4π³+π²+π))."),
    ("工程师可直接使用结论，无需理解SCVC几何推导。", "Engineers may directly use the conclusions without understanding the SCVC geometric derivation."),
    ("SCVC工程极限", "SCVC Engineering Limit"),
    ("工程结论", "Engineering Conclusions"),
    ("速查表", "reference table"),
    ("来源", "Source"),
    ("验证", "Verification"),
    ("实验", "Experiment"),
    ("理论", "theory"),
]

# ========== E5 Catalysis ==========
T_E5 = T_COMMON + [
    ("E5：催化反应速率上限 + 催化剂设计方向", "E5: Catalytic Reaction Rate Ceiling + Catalyst Design Directions"),
    ("催化活化能下限", "Catalytic Activation Energy Lower Bound"),
    ("过渡态理论框架", "Transition State Theory Framework"),
    ("速率常数：k = (k_B T / h) · exp(−ΔG‡ / k_B T)", "Rate constant: k = (k_B T / h) · exp(−ΔG‡ / k_B T)"),
    ("这是\"零势垒\"的频率上限", 'This is the frequency ceiling at "zero barrier"'),
    ("任何催化反应的 TOF 不能超过此值", "The TOF of any catalytic reaction cannot exceed this value"),
    ("TOF上限 vs 活化能 E_a:", "TOF Ceiling vs. Activation Energy E_a:"),
    ("几乎不能反应", "essentially no reaction"),
    ("Sabatier原理的SCVC版本", "SCVC Version of the Sabatier Principle"),
    ("Sabatier: 催化剂与中间体的结合\"不太强、不太弱\" → 火山曲线", 'Sabatier: catalyst-intermediate binding "not too strong, not too weak" → volcano curve'),
    ("SCVC键能范围: 3.6-9.8 eV → 中间体结合能必须在此范围内可调", "SCVC bond-energy range: 3.6-9.8 eV → intermediate binding energies must be tunable within this range"),
    ("对于 A₂ + B → 2AB 型反应（解离+重组两步）:", "For A₂ + B → 2AB type reactions (dissociation + recombination, two steps):"),
    ("最佳吸附能：ΔG_opt ≈ ΔG_rxn / 2（对称反应）", "Optimal adsorption energy: ΔG_opt ≈ ΔG_rxn / 2 (symmetric reaction)"),
    ("偏离最优 → 活化能上升，速率沿火山曲线下降", "Deviation from optimum → activation energy rises, rate falls along the volcano curve"),
    ("SCVC定量约束：", "SCVC Quantitative Constraints:"),
    ("氧吸附：O* 结合能 ∼3-5 eV（O=O键的一半附近）", "Oxygen adsorption: O* binding energy ∼3-5 eV (near half the O=O bond)"),
    ("氮吸附：N* 结合能 ∼4-5 eV → 为NRR催化剂的靶标窗口", "Nitrogen adsorption: N* binding energy ∼4-5 eV → target window for NRR catalysts"),
    ("碳吸附：C* 结合能 ∼2-4 eV", "Carbon adsorption: C* binding energy ∼2-4 eV"),
    ("最强键的催化挑战：N₂固氮", "The Strongest-Bond Catalysis Challenge: N₂ Fixation"),
    ("N≡N 键能 = 9.8 eV（SCVC最强化学键）", "N≡N bond energy = 9.8 eV (SCVC strongest chemical bond)"),
    ("直接解离 E_a ≈ 4.9 eV（半键级近似）", "Direct dissociation E_a ≈ 4.9 eV (half-bond-order approximation)"),
    ("宇宙年龄尺度也看不到一次反应", "not a single reaction event would occur on the age-of-universe timescale"),
    ("催化后 E_a ≈ 0.3-0.5 eV → TOF ≈ 10⁴-10⁸ s⁻¹ → 增益 ~10⁷³×", "After catalysis E_a ≈ 0.3-0.5 eV → TOF ≈ 10⁴-10⁸ s⁻¹ → amplification ~10⁷³×"),
    ("尚未达到SCVC允许的活化能下限", "Has not yet reached the activation-energy lower bound permitted by SCVC"),
    ("理论上有 2-10× 的速率提升空间（通过调优N*结合能）", "Theoretically 2-10× rate improvement headroom (by tuning N* binding energy)"),
    ("电催化上限", "Electrocatalysis Ceiling"),
    ("OER（析氧）：2H₂O → O₂ + 4H⁺ + 4e⁻", "OER (Oxygen Evolution): 2H₂O → O₂ + 4H⁺ + 4e⁻"),
    ("平衡电位: E⁰ = 1.23 V", "Equilibrium potential: E⁰ = 1.23 V"),
    ("四步质子-电子转移，中间体：*OH, *O, *OOH", "Four-step proton-electron transfer, intermediates: *OH, *O, *OOH"),
    ("普遍标度关系（所有氧化物表面）：", "Universal scaling relation (all oxide surfaces):"),
    ("从标度关系推导最小过电位：", "Deriving minimum overpotential from the scaling relation:"),
    ("理想分步 ΔG = 4.92/4 = 1.23 eV", "Ideal stepwise ΔG = 4.92/4 = 1.23 eV"),
    ("标度约束 η_min(OER) = (3.2 − 2×1.23)/2 ≈ 0.37 V", "Scaling constraint η_min(OER) = (3.2 − 2×1.23)/2 ≈ 0.37 V"),
    ("OER理论最小过电位 ≈ 0.37 V", "OER theoretical minimum overpotential ≈ 0.37 V"),
    ("最佳催化剂（IrO₂, RuO₂）: η ≈ 0.25-0.35 V → 已接近极限！", "Best catalysts (IrO₂, RuO₂): η ≈ 0.25-0.35 V → already near the limit!"),
    ("除非打破*OOH-*OH标度关系，否则无法接近0 → SCVC不禁止打破，但需要非常规活性位点", "Cannot approach zero unless the *OOH-*OH scaling relation is broken → SCVC does not forbid breaking it, but requires unconventional active sites"),
    ("HER（析氢）：2H⁺ + 2e⁻ → H₂", "HER (Hydrogen Evolution): 2H⁺ + 2e⁻ → H₂"),
    ("单中间体 *H → Sabatier火山曲线", "Single intermediate *H → Sabatier volcano curve"),
    ("ΔG(*H) ≈ 0 为火山峰顶", "ΔG(*H) ≈ 0 is the volcano peak"),
    ("已接近峰顶 (ΔG_H ≈ -0.09 eV)，交换电流 ~1 mA/cm²", "Already near the peak (ΔG_H ≈ -0.09 eV), exchange current ~1 mA/cm²"),
    ("HER理论最小过电位 ≈ 0 V — 已基本实现（Pt）", "HER theoretical minimum overpotential ≈ 0 V — essentially already achieved (Pt)"),
    ("金属-H键可在eV量级宽范围调谐 → 更多材料可达到峰顶", "Metal-H bonds can be tuned over a wide eV-scale range → more materials can reach the peak"),
    ("ORR（氧还原）：O₂ + 4H⁺ + 4e⁻ → 2H₂O", "ORR (Oxygen Reduction): O₂ + 4H⁺ + 4e⁻ → 2H₂O"),
    ("与OER共用标度关系 → **最小过电位 ≈ 0.37 V**", "Shares scaling relation with OER → **Minimum overpotential ≈ 0.37 V**"),
    ("提升空间有限（~0.1-0.2 V），需打破标度", "Limited headroom (~0.1-0.2 V); scaling must be broken"),
    ("NRR（氮还原）：N₂ + 6H⁺ + 6e⁻ → 2NH₃", "NRR (Nitrogen Reduction): N₂ + 6H⁺ + 6e⁻ → 2NH₃"),
    ("六电子过程，多种中间体 → 标度约束复杂", "Six-electron process, multiple intermediates → complex scaling constraints"),
    ("理论最小过电位 ≈ 0.4-0.6 V", "Theoretical minimum overpotential ≈ 0.4-0.6 V"),
    ("最大敌人不是标度，是HER竞争：", "The greatest enemy is not scaling but HER competition:"),
    ("动力学历程远短于NRR (E⁰≈0 V 但需6e⁻)", "kinetic pathway far shorter than NRR (E⁰≈0 V but requires 6e⁻)"),
    ("当前NRR法拉第效率 < 10%（大多数 < 1%）", "Current NRR Faradaic efficiency < 10% (majority < 1%)"),
    ("提升方向：抑制HER（疏水表面、非水系电解液、分子催化剂）", "Direction for improvement: suppress HER (hydrophobic surfaces, non-aqueous electrolytes, molecular catalysts)"),
    ("电催化过电位总汇", "Electrocatalysis Overpotential Summary"),
    ("反应     E⁰(V)    η_min(V)   当前最佳 η(V)   距极限差距", "Reaction     E⁰(V)    η_min(V)   Current Best η(V)   Gap to Limit"),
    ("已触顶 ✓", "At ceiling ✓"),
    ("极小 (~0.1)", "Minimal (~0.1)"),
    ("中等 (FE瓶颈)", "Moderate (FE bottleneck)"),
    ("光催化", "Photocatalysis"),
    ("光解水：2H₂O → 2H₂ + O₂, ΔG = 4.92 eV (4×1.23 V)", "Water Photolysis: 2H₂O → 2H₂ + O₂, ΔG = 4.92 eV (4×1.23 V)"),
    ("带隙要求：", "Bandgap requirements:"),
    ("热力学最低: E_g > 1.23 + η_OER + η_HER ≈ 1.23 + 0.37 + 0 ≈ 1.60 eV", "Thermodynamic minimum: E_g > 1.23 + η_OER + η_HER ≈ 1.23 + 0.37 + 0 ≈ 1.60 eV"),
    ("实际最低 (含能带边位置匹配 + 动力学余量): E_g ≈ 1.8-2.0 eV", "Practical minimum (including band-edge position matching + kinetic margin): E_g ≈ 1.8-2.0 eV"),
    ("SCVC带隙范围: 0-15 eV → 最优带隙材料的存在无物理障碍", "SCVC bandgap range: 0-15 eV → existence of optimal-bandgap materials has no physical barrier"),
    ("AM1.5太阳能谱利用：", "AM1.5 solar spectrum utilization:"),
    ("约40%光子可用", "~40% of photons usable"),
    ("约30%光子可用", "~30% of photons usable"),
    ("约15%光子可用", "~15% of photons usable"),
    ("STH（Solar-to-Hydrogen）理论效率：", "STH (Solar-to-Hydrogen) theoretical efficiency:"),
    ("无过电位理想情况:  ~30%", "Ideal case without overpotential:  ~30%"),
    ("含标度过电位 (η=0.37V):  ~20-25%", "Including scaling overpotential (η=0.37V):  ~20-25%"),
    ("当前最佳粉末光催化剂:  ~1-2%", "Current best powder photocatalyst:  ~1-2%"),
    ("PV+电解槽混合系统:     ~30% (已达理论极限！)", "PV+electrolyzer hybrid system:     ~30% (Already at theoretical limit!)"),
    ("粉末光催化离SCVC极限还有 ~20× 差距", "Powder photocatalysis still ~20× from SCVC limit"),
    ("瓶颈在于：(1) 体相复合，(2) 表面反应动力学，(3) 逆反应抑制", "Bottlenecks: (1) bulk recombination, (2) surface reaction kinetics, (3) reverse reaction suppression"),
    ("PV+电解槽混合系统已触及极限 → 直接光催化的优势在于系统简化，非效率", "PV+electrolyzer hybrid system already at the limit → the advantage of direct photocatalysis is system simplicity, not efficiency"),
    ("人工光合作用：CO₂ + H₂O → 燃料 + O₂", "Artificial Photosynthesis: CO₂ + H₂O → fuel + O₂"),
    ("CO₂还原过电位远大于H₂O还原（~0.5-1.0 V vs ~0 V）", "CO₂ reduction overpotential far exceeds H₂O reduction (~0.5-1.0 V vs ~0 V)"),
    ("C-C耦合形成C₂+产物：C-C键能 3.6 eV，但在光电辅助下可及", "C-C coupling to form C₂+ products: C-C bond energy 3.6 eV, but accessible with photoelectrochemical assistance"),
    ("SCVC键能范围 (3.6-9.8 eV) 覆盖所有CO₂还原产物的键能", "SCVC bond-energy range (3.6-9.8 eV) covers the bond energies of all CO₂ reduction products"),
    ("全反应效率理论上限 ≈ 15-20%（因CO₂还原的更高过电位）", "Full-reaction theoretical efficiency ceiling ≈ 15-20% (due to higher overpotential for CO₂ reduction)"),
    ("当前最佳 < 5%", "Current best < 5%"),
    ("已接近SCVC极限的反应（改进空间 < 2×）", "Reactions Already Near SCVC Limits (improvement headroom < 2×)"),
    ("反应               当前最优        SCVC极限      评估", "Reaction               Current Best        SCVC Limit      Assessment"),
    ("HER (酸性)         Pt, η≈0          η≈0         触顶 ☑", "HER (acidic)         Pt, η≈0          η≈0         At ceiling ☑"),
    ("OER (酸性)         IrO₂, η≈0.25    η≈0.37      接近极限", "OER (acidic)         IrO₂, η≈0.25    η≈0.37      Near limit"),
    ("ORR (酸性)         Pt₃Ni, η≈0.25   η≈0.37      接近极限", "ORR (acidic)         Pt₃Ni, η≈0.25   η≈0.37      Near limit"),
    ("合成氨 (H-B)       Fe/Ru, ~90%转化  100%转化    接近平衡", "Ammonia synthesis (H-B) Fe/Ru, ~90% conv  100% conv    Near equilibrium"),
    ("这些方向的催化剂研发应转向\"降成本/增稳定性\"，而非追求更高活性", 'Catalyst R&D in these directions should pivot to "cost reduction / stability enhancement" rather than pursuing higher activity'),
    ("有数量级提升空间的反应", "Reactions With Order-of-Magnitude Headroom"),
    ("反应               当前水平          SCVC允许         差距", "Reaction               Current Level          SCVC Permits         Gap"),
    ("NRR (常温常压)     FE<10%, 产率低    FE可达100%        10-100×", "NRR (ambient)        FE<10%, low yield    FE up to 100%        10-100×"),
    ("光解水 (粉末)      STH 1-2%          STH 20-25%       10-20×", "Water photolysis (powder) STH 1-2%      STH 20-25%       10-20×"),
    ("CO₂还原 (光催化)   <5% 全反应        ~15-20%          3-5×", "CO₂ reduction (photocatalytic) <5% full rxn    ~15-20%          3-5×"),
    ("碱/中性 OER        3d金属氧化物      η≈0.37           2-5×", "Alkaline/neutral OER   3d metal oxides      η≈0.37           2-5×"),
    ("\"氮还原常温常压\"可行性判定", '"Ambient NRR" Feasibility Assessment'),
    ("SCVC判定：物理允许 ✓", "SCVC Verdict: Physically permitted ✓"),
    ("条件：", "Conditions:"),
    ("N₂吸附活化：活性位点需将N≡N键从9.8 eV弱化至 ~2-3 eV（化学吸附可做到）", "N₂ adsorption activation: active site must weaken the N≡N bond from 9.8 eV to ~2-3 eV (chemisorption can achieve this)"),
    ("顺序加氢路径：*N₂ → *N₂H → *N₂H₂ → ... → 2NH₃", "Sequential hydrogenation pathway: *N₂ → *N₂H → *N₂H₂ → ... → 2NH₃"),
    ("每一步 E_a < 0.5 eV → TOF ~10⁴ s⁻¹ → 可行", "Each step E_a < 0.5 eV → TOF ~10⁴ s⁻¹ → feasible"),
    ("HER抑制：必须将 H* 吸附能调离火山峰顶（牺牲HER活性）", "HER suppression: must tune H* adsorption energy away from the volcano peak (sacrificing HER activity)"),
    ("电子/质子耦合传递：需要适当的介质", "Coupled electron/proton transfer: requires appropriate medium"),
    ("路线建议：", "Route Recommendations:"),
    ("酶催化（固氮酶FeMo-cofactor）：自然界已实现常温常压NRR", "Enzyme catalysis (nitrogenase FeMo-cofactor): nature already achieves ambient NRR"),
    ("单原子催化剂（SACs）：打破标度关系的最大希望", "Single-atom catalysts (SACs): greatest hope for breaking scaling relations"),
    ("Li介导NRR：利用Li₃N作为中间体绕过N₂直接解离", "Li-mediated NRR: uses Li₃N as intermediate to bypass direct N₂ dissociation"),
    ("等离子体辅助：利用热电子激发N₂振动 → 降低有效E_a", "Plasma-assisted: uses hot electrons to excite N₂ vibrations → reduces effective E_a"),
    ("催化剂设计方向（来自SCVC约束）", "Catalyst Design Directions (from SCVC Constraints)"),
    ("打破标度关系 = 超越极限的关键", "Breaking scaling relations = the key to surpassing limits"),
    ("方法：单原子催化剂、受限环境（MOF/COF孔道）、电场效应", "Methods: single-atom catalysts, confined environments (MOF/COF pores), electric-field effects"),
    ("SCVC涡旋环视角：活性位点的拓扑环境改变电子Biot-Savart耦合", "SCVC vortex-ring perspective: the topological environment of the active site alters electronic Biot-Savart coupling"),
    ("活性位点电子结构可调范围", "Tunable range of active-site electronic structure"),
    ("d带中心可调域：~5-10 eV（由金属-配体键能决定）", "d-band center tunable domain: ~5-10 eV (determined by metal-ligand bond energies)"),
    ("覆盖SCVC 3.6-9.8 eV 的完整键能窗口", "Covers the full SCVC 3.6-9.8 eV bond-energy window"),
    ("不应该追求的方向", "Directions Not Worth Pursuing"),
    ("纯金属表面OER/ORR：已被IrO₂/Pt₃Ni逼近极限", "Pure metal surface OER/ORR: already pushed to the limit by IrO₂/Pt₃Ni"),
    ("水溶液中NRR无HER抑制剂：法拉第效率必然 < 1%", "Aqueous NRR without HER inhibitor: Faradaic efficiency inevitably < 1%"),
    ("催化极限由标度关系决定，而标度关系来自化学键的普遍性。", "Catalysis limits are determined by scaling relations, which arise from the universality of chemical bonds."),
    ("SCVC框架将键能锁定在3.6-9.8 eV，由此导出所有催化边界。", "The SCVC framework locks bond energies at 3.6-9.8 eV, from which all catalytic boundaries are derived."),
    ("\"打破标度\"是超越极限的唯一路径，SCVC不禁止但未提供具体配方。", '"Breaking scaling" is the only path to surpassing limits; SCVC does not forbid it but does not provide a specific recipe.'),
]

translate_file(
    os.path.join(cn_dir, "卷1_材料与结构", "E5_催化上限.md"),
    os.path.join(en_dir, "Vol1_Materials_Structures", "E5_Catalysis_Ceiling.md"),
    T_E5
)
print("=== E5 done ===")
