import sys
sys.stdout.reconfigure(encoding="utf-8")

out = r"C:\Users\20606\Documents\Codex\A\微分几何\Koide_金标准_数值积分报告.md"

lines = []
def p(s=""):
    lines.append(s)

p("# Koide sqrt(2) Gold Standard Test -- sigma_CP^2 approx 0.06 Numerical Integration Report")
p("")
p("## 0. Document Info")
p("")
p("- **Source document**: `23_Koide_GoldStandard_sigma006_NumericalIntegration.md`")
p("- **Computation date**: 2026-07-21")
p("- **Method**: Python + SciPy `quad` adaptive numerical integration")
p("- **Output files**: this report + `work/koide_integration_results.json`")
p("")
p("---")
p("")
p("## 1. Theoretical Framework")
p("")
p("### 1.1 Geometric Setup")
p("")
p("- **Manifold**: CP^2 (complex projective plane)")
p("- **Metric**: Fubini-Study (holomorphic sectional curvature = 4)")
p("- **Volume element**: dvol = 2*pi^2 * r^3 / (1+r^2)^3 * dr  (angular part integrated out)")
p("- **Total volume**: Vol(CP^2) = pi^2 / 2")
p("- **Coordinates**: r^2 = |w1|^2 + |w2|^2,  w1, w2 in C (inhomogeneous coordinates)")
p("")
p("### 1.2 Angular Integration Details")
p("")
p("Parametrization:")
p("")
p("  w1 = r cos(theta/2) e^{i(psi+phi)/2},   w2 = r sin(theta/2) e^{i(psi-phi)/2}")
p("")
p("Angular measure: (1/8) sin(theta) dtheta dphi dpsi")
p("Integration domain: 0<=theta<=pi, 0<=phi<=2pi, 0<=psi<=4pi")
p("")
p("Key angular integrals:")
p("")
p("  integral_{S^3} |w1|^2 * (1/8) sin(theta) dtheta dphi dpsi = pi^2 * r^2")
p("  integral_{S^3} |w2|^2 * (1/8) sin(theta) dtheta dphi dpsi = pi^2 * r^2")
p("  integral_{S^3} 1       * (1/8) sin(theta) dtheta dphi dpsi = 2*pi^2")
p("")
p("### 1.3 LLL Wave Functions (k=1 monopole, L^2 normalized)")
p("")
p("This report uses **standard L^2 normalization** (integral_{CP^2} |psi|^2 dvol = 1):")
p("")
p("  psi_0 = N0 / (1+r^2)^(3/2),   N0^2 = 20/pi^2  ~ 2.0264")
p("  psi_1 = N1*w1 / (1+r^2)^(3/2), psi_2 = N1*w2 / (1+r^2)^(3/2),  N1^2 = 60/pi^2 ~ 6.0793")
p("")
p("> !! IMPORTANT: The source document gives N0~0.4504, N1~0.1856. These are NOT the standard")
p("> L^2 normalization constants. Using them gives integral|psi_0|^2 dvol ~ 0.100 != 1,")
p("> causing the three masses to never become degenerate as sigma->infinity, which is")
p("> physically inconsistent. The correct normalization follows from:")
p(">")
p(">   integral_0^inf r^3/(1+r^2)^6 dr = 1/40")
p(">   integral_0^inf r^5/(1+r^2)^6 dr = 1/60")
p("")
p("### 1.4 Vortex Profile")
p("")
p("  Phi(r) = Phi_0 * exp(-r^2 / (2*sigma^2)),   sigma_CP2 ~ 0.063")
p("")
p("(Phi_0 normalization cancels in the ratios c1*R/c0 and K)")
p("")
p("### 1.5 Overlap Integrals -> Masses -> SU(3) Projection")
p("")
p("  I_i = integral_{CP^2} |psi_i|^2 * Phi(r) * dvol")
p("  m_i = I_i^2")
p("")
p("  I_0 = 40 * integral_0^inf Phi(r) * r^3/(1+r^2)^6 * dr")
p("  I_1 = I_2 = 60 * integral_0^inf Phi(r) * r^5/(1+r^2)^6 * dr")
p("")
p("SU(3) projection hypothesis:  sqrt(m_i) = c0 + c1 * n_hat . w_i")
p("")
p("where w_i are the SU(3) fundamental representation weights (|w_i| = R = 1/sqrt(3)):")
p("")
p("  w_0 = (1/2, 1/(2*sqrt(3)))")
p("  w_1 = (-1/2, 1/(2*sqrt(3)))")
p("  w_2 = (0, -1/sqrt(3))")
p("")
p("### 1.6 Analytic Relation Verified")
p("")
p("From sum w_i = 0:  c0 = (1/3) * sum sqrt(m_i)")
p("")
p("From sum (n_hat . w_i)^2 = 1/2 (for any n_hat):")
p("")
p("  K := sum m_i / (sum sqrt(m_i))^2  =  1/3 + c1^2 / (18*c0^2)")
p("")
p("Setting K = 2/3 gives c1/c0 = sqrt(6), i.e.:")
p("")
p("  c1*R / c0  =  c1/(c0*sqrt(3))  =  sqrt(6)/sqrt(3)  =  sqrt(2)")
p("")
p("> [CHECK] Analytic verification: c1*R/c0 = sqrt(2)  <==>  K = 2/3")
p("")

print("Phase 1 written, continuing...")

with open(out, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print("OK, part 1 done")
